// Package tlsbootstrap provides zero-friction self-signed certificate
// generation for development and internal deployments.
//
// It is NOT intended for production: self-signed certs trigger client trust
// warnings, and operators should prefer TLS_CERT_FILE/TLS_KEY_FILE backed by a
// real CA (Let's Encrypt, internal PKI, cert-manager, etc.) for anything
// internet-facing.
package tlsbootstrap

import (
	"crypto/ecdsa"
	"crypto/elliptic"
	"crypto/rand"
	"crypto/x509"
	"crypto/x509/pkix"
	"encoding/pem"
	"errors"
	"fmt"
	"log/slog"
	"math/big"
	"net"
	"os"
	"path/filepath"
	"sync"
	"time"
)

const (
	certFileName = "cert.pem"
	keyFileName  = "key.pem"

	// certValidity is how long a freshly generated cert is valid.
	certValidity = 10 * 365 * 24 * time.Hour
	// renewBefore: regenerate if the cached cert expires within this window.
	renewBefore = 24 * time.Hour
)

// fsMu serialises cache-directory writes across concurrent callers in the
// same process, so two goroutines never race on the same cert/key files.
var fsMu sync.Mutex

// EnsureSelfSignedCert creates (or loads if valid) a self-signed cert pair
// cached under cacheDir. It returns absolute paths to the cert.pem and key.pem
// files that can be passed directly to
// http.Server.ListenAndServeTLS / credentials.NewServerTLSFromFile.
//
// The generated certificate has:
//   - ECDSA P-256 key (fast, widely supported, HTTP/2 + gRPC compatible).
//   - 10-year validity (self-signed, rotated by deleting the cache dir).
//   - CN=otelcontext, self-CA (IsCA=true) so clients can pin this cert.
//   - SANs: localhost, the OS hostname (best-effort), and IPs 127.0.0.1, ::1.
//   - ExtKeyUsage: ServerAuth + ClientAuth (covers gRPC + HTTP server use).
//
// On the first invocation, a loud INFO log is emitted reminding the operator
// this is a development-mode cert. Subsequent invocations that reuse a valid
// cached cert log at DEBUG only.
func EnsureSelfSignedCert(cacheDir string) (certPath, keyPath string, err error) {
	// Intra-process fast path: cheap mutex prevents two goroutines in this
	// process from even contending on the filesystem lock below.
	fsMu.Lock()
	defer fsMu.Unlock()

	if cacheDir == "" {
		return "", "", errors.New("tlsbootstrap: cacheDir must not be empty")
	}

	// 0700 — private material.
	if err := os.MkdirAll(cacheDir, 0o700); err != nil {
		return "", "", fmt.Errorf("tlsbootstrap: create cache dir %q: %w", cacheDir, err)
	}

	certPath = filepath.Join(cacheDir, certFileName)
	keyPath = filepath.Join(cacheDir, keyFileName)

	// Fast path without cross-process lock: a valid cached cert needs no
	// generation and thus no writer coordination. Re-checked under the lock
	// below to close the TOCTOU gap.
	if reuseValid(certPath, keyPath) {
		slog.Debug("tlsbootstrap: reusing cached self-signed cert", "cert", certPath)
		return certPath, keyPath, nil
	}

	// Cross-process serialisation: two OtelContext instances sharing the same
	// TLS_CACHE_DIR would otherwise race on the cert.pem/key.pem rename. Hold
	// an exclusive lock on tls.lock for the duration of the write.
	release, lockErr := acquireDirLock(cacheDir)
	if lockErr != nil {
		return "", "", lockErr
	}
	defer release()

	// Re-check under the lock — another process may have generated the cert
	// while we were waiting.
	if reuseValid(certPath, keyPath) {
		slog.Debug("tlsbootstrap: reusing cert generated by peer process", "cert", certPath)
		return certPath, keyPath, nil
	}

	if err := generate(certPath, keyPath); err != nil {
		return "", "", err
	}

	slog.Info("⚠️  tlsbootstrap: generated new self-signed TLS cert — DEV MODE ONLY, not for production",
		"cert", certPath,
		"key", keyPath,
		"validity", certValidity.String(),
	)

	return certPath, keyPath, nil
}

// reuseValid reports whether both files on disk parse as a valid,
// unexpired cert/key pair with the SANs we expect.
func reuseValid(certPath, keyPath string) bool {
	certPEM, err := os.ReadFile(certPath) // #nosec G304 -- path assembled from trusted cacheDir
	if err != nil {
		return false
	}
	if _, err := os.ReadFile(keyPath); err != nil { // #nosec G304
		return false
	}

	block, _ := pem.Decode(certPEM)
	if block == nil || block.Type != "CERTIFICATE" {
		return false
	}
	cert, err := x509.ParseCertificate(block.Bytes)
	if err != nil {
		return false
	}
	if time.Now().Add(renewBefore).After(cert.NotAfter) {
		return false
	}
	if !hasExpectedSANs(cert) {
		return false
	}
	return true
}

// hasExpectedSANs ensures the cached cert covers the minimum set we always
// request: "localhost" DNS name and both loopback IPs. Hostname drift
// (container rename etc.) is ignored — only the constants matter.
func hasExpectedSANs(cert *x509.Certificate) bool {
	var hasLocalhost bool
	for _, d := range cert.DNSNames {
		if d == "localhost" {
			hasLocalhost = true
			break
		}
	}
	if !hasLocalhost {
		return false
	}
	var has127, hasV6 bool
	for _, ip := range cert.IPAddresses {
		if ip.Equal(net.IPv4(127, 0, 0, 1)) {
			has127 = true
		}
		if ip.Equal(net.IPv6loopback) {
			hasV6 = true
		}
	}
	return has127 && hasV6
}

// generate writes a brand new cert/key pair to the given paths.
func generate(certPath, keyPath string) error {
	priv, err := ecdsa.GenerateKey(elliptic.P256(), rand.Reader)
	if err != nil {
		return fmt.Errorf("tlsbootstrap: generate key: %w", err)
	}

	serialLimit := new(big.Int).Lsh(big.NewInt(1), 128)
	serial, err := rand.Int(rand.Reader, serialLimit)
	if err != nil {
		return fmt.Errorf("tlsbootstrap: serial: %w", err)
	}

	hostname, _ := os.Hostname() // best-effort; empty is fine

	dnsNames := []string{"localhost"}
	if hostname != "" && hostname != "localhost" {
		dnsNames = append(dnsNames, hostname)
	}

	tmpl := &x509.Certificate{
		SerialNumber:          serial,
		Subject:               pkix.Name{CommonName: "otelcontext"},
		NotBefore:             time.Now().Add(-1 * time.Hour),
		NotAfter:              time.Now().Add(certValidity),
		KeyUsage:              x509.KeyUsageDigitalSignature | x509.KeyUsageCertSign,
		ExtKeyUsage:           []x509.ExtKeyUsage{x509.ExtKeyUsageServerAuth, x509.ExtKeyUsageClientAuth},
		BasicConstraintsValid: true,
		IsCA:                  true,
		DNSNames:              dnsNames,
		IPAddresses:           []net.IP{net.IPv4(127, 0, 0, 1), net.IPv6loopback},
	}

	der, err := x509.CreateCertificate(rand.Reader, tmpl, tmpl, &priv.PublicKey, priv)
	if err != nil {
		return fmt.Errorf("tlsbootstrap: create certificate: %w", err)
	}

	certPEM := pem.EncodeToMemory(&pem.Block{Type: "CERTIFICATE", Bytes: der})

	keyDER, err := x509.MarshalECPrivateKey(priv)
	if err != nil {
		return fmt.Errorf("tlsbootstrap: marshal key: %w", err)
	}
	keyPEM := pem.EncodeToMemory(&pem.Block{Type: "EC PRIVATE KEY", Bytes: keyDER})

	// Write key first at 0600, then cert at 0644. Use atomic rename so a
	// crash mid-write never leaves a truncated file behind.
	if err := writeAtomic(keyPath, keyPEM, 0o600); err != nil {
		return err
	}
	if err := writeAtomic(certPath, certPEM, 0o644); err != nil {
		return err
	}
	return nil
}

// writeAtomic writes data to path via temp-file + rename, so concurrent
// readers never see a partial file.
func writeAtomic(path string, data []byte, mode os.FileMode) error {
	dir := filepath.Dir(path)
	tmp, err := os.CreateTemp(dir, filepath.Base(path)+".tmp-*")
	if err != nil {
		return fmt.Errorf("tlsbootstrap: temp file: %w", err)
	}
	tmpName := tmp.Name()
	// Best-effort cleanup on failure.
	defer func() { _ = os.Remove(tmpName) }()

	if _, err := tmp.Write(data); err != nil {
		_ = tmp.Close()
		return fmt.Errorf("tlsbootstrap: write %q: %w", path, err)
	}
	if err := tmp.Chmod(mode); err != nil {
		_ = tmp.Close()
		return fmt.Errorf("tlsbootstrap: chmod %q: %w", path, err)
	}
	if err := tmp.Close(); err != nil {
		return fmt.Errorf("tlsbootstrap: close %q: %w", path, err)
	}
	if err := os.Rename(tmpName, path); err != nil {
		return fmt.Errorf("tlsbootstrap: rename %q: %w", path, err)
	}
	return nil
}
